CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100),
	`email` varchar(320) NOT NULL,
	`phone` varchar(20),
	`zip` varchar(10),
	`eventId` varchar(64),
	`sourceTool` varchar(64) DEFAULT 'ai_scanner',
	`hasQuote` enum('yes','no','unknown') DEFAULT 'unknown',
	`windowCount` int,
	`timeline` varchar(64),
	`budgetRange` varchar(64),
	`projectType` varchar(64),
	`callbackPreference` varchar(64),
	`callbackTime` varchar(64),
	`utmSource` varchar(255),
	`utmMedium` varchar(255),
	`utmCampaign` varchar(255),
	`utmTerm` varchar(255),
	`utmContent` varchar(255),
	`fbclid` varchar(255),
	`gclid` varchar(255),
	`fbp` varchar(255),
	`fbc` varchar(255),
	`status` enum('new','contacted','qualified','converted','lost') DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`eventId` varchar(64),
	`quoteUrl` varchar(1024),
	`filePath` varchar(512),
	`fileMime` varchar(64),
	`fileSize` int,
	`originalFilename` varchar(255),
	`status` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`overallScore` int,
	`safetyScore` int,
	`scopeScore` int,
	`priceScore` int,
	`finePrintScore` int,
	`warrantyScore` int,
	`pricePerOpening` varchar(64),
	`warnings` json,
	`missingItems` json,
	`summary` text,
	`rawSignals` json,
	`modelVersion` varchar(64),
	`processingMs` int,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `scans` ADD CONSTRAINT `scans_leadId_leads_id_fk` FOREIGN KEY (`leadId`) REFERENCES `leads`(`id`) ON DELETE no action ON UPDATE no action;